name: Android CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - run: chmod +x gradlew
      - run: ./gradlew lintDebug --stacktrace

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: |
            app/build/reports/lint-results*.html
            app/build/reports/lint/*.html

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - run: chmod +x gradlew
      - run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/**/index.html

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - run: chmod +x gradlew
      - run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK (for deploy job)
        uses: actions/upload-artifact@v4
        with:
          name: build-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload All Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            app/build/reports/lint-results*.html
            app/build/reports/lint/*.html
            app/build/reports/tests/**/index.html
            app/build/reports/androidTests/connected/**

  deploy:
    name: Deploy APK
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download built APK
        uses: actions/download-artifact@v4
        with:
          name: build-apk
          path: ./output

      - name: Deploy APK
        run: |
          echo "🚀 Deploying APK..."
          ls -lh ./output
          # Example deployment (Firebase App Distribution):
          # firebase appdistribution:distribute ./output/app-debug.apk \
          #   --app ${{ secrets.FIREBASE_APP_ID }} \
          #   --groups testers \
          #   --token ${{ secrets.FIREBASE_TOKEN }}
